version: "3.3"

services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbbanner
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./creating_tablesDB.sql:/docker-entrypoint-initdb.d/creating_tablesDB.sql
      - ./inserting_data_into_tables.sql:/docker-entrypoint-initdb.d/inserting_data_into_tables.sql
    ports:
      - "5432:5432"
    networks:
      - ps

  test_db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - ./test_data:/var/lib/postgresql/data
      - ./creating_tablesDB.sql:/docker-entrypoint-initdb.d/creating_tablesDB.sql
      - ./inserting_data_into_tables.sql:/docker-entrypoint-initdb.d/inserting_data_into_tables.sql
    ports:
      - "5433:5432"
    networks:
      - ps

  app:
    image: prod-service:local
    container_name: ps-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ps

networks:
  ps: